### ISSUE TITLE
Problem with Travis CI Build

### ISSUE THREAD

**Issue by Zubair-Marediya** [berkeley-stat159/project-zeta#19]
@rossbar @jarrodmillman @matthew-brett 

Hi all,

We have a script called structure.py that checks if the user has the same directory structure as us. If they don't, it will make it for them. This script works fine locally, however Travis coverage fails. We removed it for now, but why does this happen and how can we fix it?

Here's the error:

<img width="719" alt="screen shot 2015-12-13 at 9 31 24 pm" src="https://cloud.githubusercontent.com/assets/9260565/11773604/1c62fe36-a1e1-11e5-863f-e458c84ca831.png">

**Comment by rossbar** [comment]
I can't find the commit that causes this in any of the forks or repos, so I can't say much - the image of the error from the coverage website doesn't really tell you much.

Run make coverage locally to get a more thorough diagnosis of what's wrong

**Comment by matthew-brett** [comment]
Did y'all get this one fixed in the end?

**Comment by Zubair-Marediya** [comment]
I believe we found an alternative solution. Thanks!
