### ISSUE TITLE
Can't merge pull requests 

### ISSUE THREAD

**Issue by Zubair-Marediya** [berkeley-stat159/project-zeta#2]
@rossbar @jarrodmillman @matthew-brett 

Hi Ross,
We followed your instructions from today and can push to our own forks. However, no one can merge the requests into berkeley-stat159/project-zeta since no one has write access.

How can we fix this?

Also, our build is unknown. Is it because we aren't listed here? https://travis-ci.org/berkeley-stat159

Best,
Team Zeta

(P.S. Matthew & Jarrod, to catch you up, we accidentally pushed 2 GB of data and it got saved into our commit history. So cloning the repo took forever. Ross was able to delete it from the history, and make us a new folder on github. However, I think we need to resync that with Travis CI and get write access for our members.)

**Comment by rossbar** [comment]
I've re-added team-zeta as collaborators - try now

**Comment by Zubair-Marediya** [comment]
Pull requests work like a charm now! Thank you! :)

How can we get the Travis Build to work?

**Comment by rossbar** [comment]
How about now?

**Comment by rossbar** [comment]
You may need to push something in order to trigger the travis build

**Comment by Zubair-Marediya** [comment]
Everything is working perfectly now! Thank you so so so much!
