### ISSUE TITLE
Travis CI being weird?

### ISSUE THREAD

**Issue by Zubair-Marediya** [berkeley-stat159/project-zeta#25]
@rossbar @matthew-brett @jarrodmillman 

Hi all,

It seems as if Travis hangs on running our tests. Would you know why it's doing this?

**Comment by matthew-brett** [comment]
No. It looks like the build is just not starting up.  I guess travis-ci is having a problem - they've had a few problems in the last couple of days : 

https://www.traviscistatus.com/

I also notice the number of Linux open-source builds dropped off a lot at about 10am this morning CA time.

So, I'm afraid you may have to merge your last few commits without travis testing for now.  Don't forget to check locally...

**Comment by Zubair-Marediya** [comment]
Alright, thanks!
