### ISSUE TITLE
Data verification

### ISSUE THREAD

**Issue by rossbar** [berkeley-stat159/project-zeta#31]
Your group has made a lot of progress here... great job! :+1: 

One thing you might consider for the data verification is to provide the user with a verification summary when the `make validate` reaches completion. Right now, you print out the verification status for each individual file, which is completely okay. In addition, I would add something at the end the prints true if every verification passed, and false if any of them didn't

**Comment by Zubair-Marediya** [comment]
<code>make validate</code> now prints a final verification status.
