### ISSUE TITLE
make data doesn't work

### ISSUE THREAD

**Issue by rossbar** [berkeley-stat159/project-zeta#47]
I get the following error when running `make data` (I'm running remotely so had to use a screencap to get the error message, sorry for the poor quality):

![zeta_error](https://cloud.githubusercontent.com/assets/1268991/11834969/e152c212-a385-11e5-981e-b161179501cf.png)

The error looks like you're calling tar with the -z option on a file that is not zipped. The -z option with tar should only be used when the file has been compressed with gzip (these files usually end with .tgz or .gz)

Please fix and push the changes (see the piazza announcement) or affix the "wontfix" label if you want us to try to proceed manually.

**Comment by Zubair-Marediya** [comment]
Hi Ross,

We edited our Makefile  to correct the -z flag, however now Travis isn't passing for both versions of Python. Here's what it shows:

![error1](https://cloud.githubusercontent.com/assets/9260565/11838019/3feb0b00-a399-11e5-8e02-8472d751debd.PNG)

And here are the only changes we made:

![changes1](https://cloud.githubusercontent.com/assets/9260565/11838027/49b8c8d4-a399-11e5-9fd4-b8598331f3b8.PNG)

Do you know what's going on? If it's some dependency issue with libraries, how can we get Travis to install them? Does this mean we have to tamper with the travis.yml file?

**Comment by matthew-brett** [comment]
Hmm - I'm getting errors on `apt-get update` myself : https://travis-ci.org/matthew-brett/travis-wheel-builder/jobs/97180487

I think this might be a temporary travis problem.

**Comment by matthew-brett** [comment]
For now, try adding `sudo apt-get update` before your line starting `sudo apt-get install` in the `.travis.yml` file.

**Comment by rossbar** [comment]
Try testing locally: re-clone your project in a fresh directory and run the commands in your README in the order you specify (preferrably on a linux machine so mac compatibility issues will be caught). If everything runs without errors, notify us and I will pull and re-run the project.

**Comment by Zubair-Marediya** [comment]
@rossbar @matthew-brett @jarrodmillman 

Hi all,

We ran everything locally and it was reproducible. However, will you be running it remotely on a Linux box? I tried simulating that by running everything on the SCF's Linux cluster and here's what I got:

![displayerror](https://cloud.githubusercontent.com/assets/9260565/11877692/c7402178-a4a5-11e5-9a3e-af11939e6e77.PNG)

One possible solution was proposed here at https://github.com/ioam/holoviews/issues/68 by adding this to the code:

```
from matplotlib import pyplot as plt
plt.switch_backend('agg')
```

Would that interfere with anyone running it locally, or with you running it remotely?

Thanks,
Zeta

**Comment by rossbar** [comment]
I am running remotely, but that shouldn't be a problem. The error you got above is because your code is trying to generate graphics, but there is no hardware to display graphics on so the renderer is getting confused.

You can fix this with the -X command to ssh, as long as the remote server is running an X server (this is true in my case, I'm not sure about the SCF though).

Thanks for taking a look, I will close the issue once the analysis completes.

**Comment by Zubair-Marediya** [comment]
So I ssh'ed with the -X flag, but it still got the same error. So I guess SCF isn't running an X server?

I also tried the trick mentioned in that link, and it worked. 

Please let me know if you get the error, and I'll edit all the scripts to follow the link's trick. 

Lastly, we just pushed our final changes to make everything reproducible. Please pull now and try out the roadmap. 

Thanks!

**Comment by rossbar** [comment]
Your analysis ran to completion without any errors. I was on commit 00d224c (I was already running before your last comment) so I don't have those final changes you mention in the previous comment. If you'd like me to re-run everything with the latest commit, let me know: if it's not going to affect your results or the paper then I don't think it's necessary. It's up to you though.

**Comment by Zubair-Marediya** [comment]
Hi Ross,

We would like to rerun it with the latest commit since it fixes something in the reproducibility of the report. 

Thanks!

**Comment by rossbar** [comment]
Okay, will do. Thanks for taking a look at this.
